- package.json
Since `winston` exports a singleton, having it as a `dependency` in `package.json` makes `winston-cloudwatch` reference the one installed under its `node_modules` and not the one installed under the application's `node_modules`. Making it a `peerDependency` solves this issue.
> Placed winston as a peerDependency (and updated version)

- index.js
- lib/cloudwatch-integration.js
CloudWatch Logs accepts JSON logs.
Allowing the log object to be sent as JSON enables the use of JSON filters within cloudwatch, http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/FilterAndPatternSyntax.html
{$.level=debug}
This pull request adds the option to send the log object as JSON.
> add option to send log object as json

- lib/cloudwatch-integration.js
The call to `describeLogStreams` didn't take `nextToken` into account, making it crash on groups with many streams. So I fixed that first by adding support for paging.
Then I noticed the `logStreamNamePrefix` option, which makes paging unnecessary in most cases. Still, it's good to have it in there.
> Adding paging to describeLogStreams

- README.md
- index.js
- lib/cloudwatch-integration.js
- package.json
Using winston-cloudwatch behind a proxy won't work, so I've added this change so you can specify the proxy server on the AWS object instance.
Let me know your thoughts. Thanks
> Adding support for a proxy server

- lib/cloudwatch-integration.js
fix getStream when there are many streams in the group by passing log StreamNamePrefix to CWL. CWL only returns the first 50 matches, so the one we just created will get missed with a broad search. For me this is currently resulting in no logs getting posted, and, worse, a memory leak: getStream never finished so upload never gets to the point of taking items out of the queue.
> fix getStream when there are many streams in the group

- index.js
To solve this isse aws/aws-sdk-js#527, I needed the ability to pass options to the `AWS.CloudWatchLogs` constructor.
If the options object contains a `awsOptions` key, this will merged and passed in to the constructor
> We can now pass AWS.CloudWatchLogs options

- lib/cloudwatch-integration.js
- test/cloudwatch-integration.js
I had three problems using this library in a production system, all three I have addressed in this PR. 
1. BUG - while under heavy load, random InvalidSequenceTokenExceptions would be returned from CW and log messages were lost. The reason is that the timer tried to send the next batch before the current one completed, so the next sequence token was not available yet. 
2. A batch with a single very large message that exceeds CW's limit for a single event would cause an error response from CW and the entire batch of messages to be lost. 
3. Even if individual messages are below the CW max for a single message, it's possible that a few messages together can add up to more than the CW limit for a single upload. This would cause an error response from CW and the entire batch of messages to be …
> Fixes a bug when under heavy load and and adds batching and truncating features 

- index.js
Check if message start with the string "uncaughtException: " and if so, send all logs immediately with callback when done.
> Send logs immediately when catching an exception

- README.md
- index.js
- lib/cloudwatch-integration.js
- package-lock.json
- test/cloudwatch-integration.js
- test/index.js
We needed the ability to specify a duration on some of our logs and we already used this library.  Let me know if there is anything I need to change.  This already includes updated tests.
There was only the one TODO in the callback of the `putRetentionPolicy` function; I didn't think it was that important we handled the callback since its default behavior to not have the retention policy anyway.
> add ability to specify a retention policy for cloudwatch logs

- .travis.yml
- index.js
- lib/cloudwatch-integration.js
- package-lock.json
- package.json
- test/index.js
This enables the transport to be used with latest `winston@3.0.0-rc1`.
- Support latest Winston while keeping compatibility with previous versions.
- Add unit test to cover the new case.
- Update all dependencies.
- Make TravisCI run on node `4.2.2`, which is the [minimum version required by `winston`](https://github.com/winstonjs/winston/blob/master/package.json#L52).
> Support Winston 3.x

- README.md
The official doc use a `require('../index')` but if it's a library it's better to import the library, I suggest a change to the `README` to use it with the `require` and the `import` method.
> Implement the correct way to use library import/require

- typescript/winston-cloudwatch.d.ts
Hi,
For me this fixes the typing errors as described in lazywithclass/winston-cloudwatch#108.
The declaration are now in the same format as described in the documentation: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html
I hoped this helped.
With kind regards
> Updated typings

- lib/cloudwatch-integration.js
- test/cloudwatch-integration.js
When having multiple instances of Winston CloudWatch transport to distinct logStreams running in parallel the submission to one logStream should not concur with the others.
In our scenario we have multiple short living loggers to different logStreams, while one transport was submitting to CloudWatch the others were skipping the submission, because they are short living when we close the logger we were losing the entries that were not sent to CloudWatch.
Illustration:
```
logger1: { logStreamName: 'stream1' }
logger2: { logStreamName: 'stream2' }
```
```
logger1.info(...);
logger2.info(...);
// logger1 starts submitting the logs
// logger2 is closed and logs are flushed
logger2.transports.find(transport => 'kthxbye' in transport).kthxbye(); 
// because logger1 is submitting the logs are …
```
> Posting events control per logStream instead of global

- lib/cloudwatch-integration.js
This limit is actually not listed in AWS's documentation https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html.
And when using it, I found that if your process is logging more than `100` messages within the `uploadRate` window constantly, this creates an always increasing back pressure in the `logEvents` queue that will eventually cause the process to run out of memory without warning.
I think we should stick to AWS actually listed limitations, as this one for example was hard to catch when using it.
> Remove limit for batch size count

- typescript/winston-cloudwatch.d.ts
`export type LogObject = { level: string; msg: string; meta?: any };` is not correct. Instead, using winston's type definition of Log object 
which is 
`  level: string;
message: string;
[optionName: string]: any;`
> winston log object types corrected

- lib/cloudwatch-integration.js
- test/cloudwatch-integration.js
According to their documentation, "the maximum batch size is 1,048,576 bytes. This size is calculated as the sum of all event messages in UTF-8, plus 26 bytes for each log event." Currently we only include the first part of size calculation. This means that any batch with more than 1868 messages will fail with an invalid parameter error because we only allow 48,576 extra bytes. Now, we'll allow you to send batches with any number of events as long as they pass AWS's limits.
> Include CloudWatch event limits

- index.js
- lib/cloudwatch-integration.js
- test/cloudwatch-integration.js
- test/index.js
- typescript/winston-cloudwatch.d.ts
This could help to have only 1 DescribeLog calls instead of 2 if a user is sure that loggroup is present
> Allow skipping ensure loggroup

- README.md
The previous URL showed general metric limits without anything regarding logs.
Have updated the README to go to the Log specific limits, as mentioned further down the page within the options section.
> Update Logs Limit Doc to correct URL

- README.md
- index.js
- lib/cloudwatch-integration.js
- package-lock.json
- package.json
- test/cloudwatch-integration.js
- test/index.js
- typescript/winston-cloudwatch.d.ts
I wanted to use aws' new modular packages instead of the full aws sdk. 
I made it so that the user only needs to have the @aws-sdk/client-cloudwatch-logs module. To do this, I had to remove the proxy option which uses the main AWS sdk. In my opinion, this project shouldn't need to touch that option anyway. I also update mocha to fix the audit issues. 
Lastly, I updated the typescript definition. `name` for transport options is optional.
> Use modular cloudwatch package instead of entire aws sdk.

- .github/workflows/main.yml
This PR configures GitHub Actions to run the test suite in Node 8 - 16.
You might want to integrate with https://coveralls.io and push the coverage reports there.
> Add GitHub Actions to run tests

- package.json
Adding @aws-sdk/client-cloudwatch-logs  as a peer dependency will ensure Serverless includes that package when it is bundling/tree shaking
> Add @aws-sdk/client-cloudwatch-logs as a peer dependency

- lib/cloudwatch-integration.js
- test/cloudwatch-integration.js
When the ensureLogGroup option is true, the log group will be created if it is missing.
Use err.name instead of err.code for AWS errors. This appears to be a consequence of using @aws-sdk (v3) instead of aws-sdk (v2).
> Fix: Create log groups when missing

- typescript/winston-cloudwatch.d.ts
Add error parameter to `kthxbye` callback function to allow better error handling when using TypeScript.
#187
> Add error parameter to kthxbye callback

- README.md
Fixes https://github.com/lazywithclass/winston-cloudwatch/issues/104 from happening again
> Fix ES6 import syntax in README

- package-lock.json
- package.json
proxy-agent was made redundant after #172, which introduced v3 of aws-sdk. This meant that any proxy-related config was done on the `AWS.CloudwatchLogs` instance, rather than on `WinstonCloudwatch`
Removing this dependency avoids a reported critical vulnerability with vm2, inherited via proxy-agent and its dependencies. Note that this vulnerability can not actually be triggered, given that winston-cloudwatch no longer uses proxy-agent.
Fixes #218
Supersedes #216
This PR is submitted as part of work for @opengovsg ([Open Government Products, Singapore](https://open.gov.sg)).
> Remove proxy-agent, not used

- index.js
- lib/cloudwatch-integration.js
- test/cloudwatch-integration.js
- test/index.js
**Stop memory leaking every stream name seen in cloudwatch-integration**
The _postingEvents variable saved every single seen streamName as a key
and these entries were never getting deleted. Since
cloudwatch-integration stores _postingEvents as a top level variable, it
gets shared between all instances of WinstonCloudWatch and leaks memory.
To fix this, delete entries for streams that are not posting events.
This is safe to do because the only place where _postingEvents entries
get read checks whether the value is falsy. If a key doesn't exist in an
object, accessing it returns `undefined` which is falsy and the code
works the same as before.
**Stop memory leaking CloudWatch sequence tokens in cloudwatch-integration**
The _nextToken variable saved every sequence token for every stream …
> Fix memory leaks in cloudwatch-integration
